# Generated by Django 5.0.6 on 2024-06-27 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("archive", "0003_resource_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(max_length=50, verbose_name="identifier"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="caption"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "license",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="license"
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="image")),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.resource",
                        verbose_name="resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "image material",
                "verbose_name_plural": "image materials",
            },
        ),
        migrations.CreateModel(
            name="TextMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(max_length=50, verbose_name="identifier"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="caption"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "license",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="license"
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.resource",
                        verbose_name="resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "text material",
                "verbose_name_plural": "text materials",
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json",
                    models.JSONField(
                        default=list,
                        help_text="Paste the full transcript in JSON format.",
                        verbose_name="JSON file",
                    ),
                ),
                (
                    "vtt",
                    models.TextField(
                        default="",
                        help_text="Paste the full transcript in VTT format.",
                        verbose_name="VTT file",
                    ),
                ),
                ("language", models.CharField(max_length=5, verbose_name="language")),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.resource",
                        verbose_name="resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "transcript",
                "verbose_name_plural": "transcripts",
            },
        ),
    ]
