# Generated by Django 5.0.6 on 2024-06-24 18:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="", max_length=200, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="last name"),
                ),
                (
                    "eastern_name_order",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the last name should appear first.",
                        verbose_name="eastern name order",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("D", "Diverse"),
                            ("N", "Not specified"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
            ],
            options={
                "verbose_name": "agent",
                "verbose_name_plural": "agents",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="MetadataKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20, verbose_name="label")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "metadata key",
                "verbose_name_plural": "metadata keys",
            },
        ),
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INT", "Interviewee"),
                            ("ITR", "Interviewer"),
                            ("CAM", "Camera"),
                            ("SND", "Sound"),
                            ("EDT", "Editor"),
                            ("OTH", "Other"),
                        ],
                        default="INT",
                        max_length=3,
                        verbose_name="type",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.agent",
                        verbose_name="agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "agency",
                "verbose_name_plural": "agencies",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=200, verbose_name="title"),
                ),
                (
                    "anon_title",
                    models.CharField(
                        default="", max_length=200, verbose_name="anonymized title"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        default="video/mp4",
                        help_text="Enter MIME type e.g. 'video/mp4'.",
                        max_length=100,
                        verbose_name="media type",
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        default="", max_length=300, verbose_name="media url"
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        default="",
                        upload_to="",
                        verbose_name="poster image",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(null=True, verbose_name="date published"),
                ),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(0), verbose_name="duration"
                    ),
                ),
                ("public", models.BooleanField(default=True, verbose_name="public")),
                (
                    "agents",
                    models.ManyToManyField(
                        through="archive.Agency",
                        to="archive.agent",
                        verbose_name="agents",
                    ),
                ),
            ],
            options={
                "verbose_name": "resource",
                "verbose_name_plural": "resources",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="EntityReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timecodes",
                    models.JSONField(
                        default=list,
                        help_text="Enter timecodes in seconds as a comma separated list, e.g.: [124.3, 210.5]",
                        verbose_name="timecodes",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entities.entity",
                        verbose_name="entity",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.resource",
                        verbose_name="resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "entity reference",
                "verbose_name_plural": "entity references",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "description",
                    models.TextField(default="", verbose_name="description"),
                ),
                (
                    "resources",
                    models.ManyToManyField(
                        to="archive.resource", verbose_name="resources"
                    ),
                ),
            ],
            options={
                "verbose_name": "collection",
                "verbose_name_plural": "collections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CharFieldMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200, verbose_name="value")),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.metadatakey",
                        verbose_name="key",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.resource",
                        verbose_name="resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "char field metadata",
                "verbose_name_plural": "char field metadata",
            },
        ),
        migrations.AddField(
            model_name="agency",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="archive.resource",
                verbose_name="resource",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["title"], name="archive_res_title_d94d90_idx"),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(fields=["name"], name="archive_col_name_311250_idx"),
        ),
    ]
