# Generated by Django 5.0.3 on 2024-03-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='anon_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
