# Generated by Django 5.0.3 on 2024-03-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
