# Generated by Django 5.0.6 on 2024-06-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="locations",
        ),
        migrations.AlterModelOptions(
            name="charfieldmetadata",
            options={
                "verbose_name": "char field metadata",
                "verbose_name_plural": "char field metadata",
            },
        ),
        migrations.AlterModelOptions(
            name="metadatakey",
            options={
                "verbose_name": "metadata key",
                "verbose_name_plural": "metadata keys",
            },
        ),
        migrations.AlterField(
            model_name="charfieldmetadata",
            name="key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="archive.metadatakey",
                verbose_name="key",
            ),
        ),
        migrations.AlterField(
            model_name="charfieldmetadata",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="archive.resource",
                verbose_name="resource",
            ),
        ),
        migrations.AlterField(
            model_name="charfieldmetadata",
            name="value",
            field=models.CharField(max_length=200, verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="metadatakey",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="metadatakey",
            name="label",
            field=models.CharField(max_length=20, verbose_name="label"),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="language",
            field=models.CharField(max_length=5, verbose_name="language"),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="archive.resource",
                verbose_name="resource",
            ),
        ),
        migrations.DeleteModel(
            name="LocationReference",
        ),
    ]
