# Generated by Django 5.0.3 on 2024-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_person_topic_archive_description_interview_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicreference',
            name='timecode',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
