# Generated by Django 5.0.6 on 2024-06-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_agent_gnd_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="type",
            field=models.CharField(
                choices=[
                    ("INTERVIEW", "Interview"),
                    ("AUDIOBOOK", "Audiobook"),
                    ("OTHER", "Other"),
                ],
                default="INTERVIEW",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
