# Generated by Django 5.0.6 on 2024-06-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_resource_anon_title"),
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationreference",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entities.location"
            ),
        ),
        migrations.AlterField(
            model_name="resourceinvolvement",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entities.person"
            ),
        ),
        migrations.AlterField(
            model_name="topicreference",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entities.topic"
            ),
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="resource",
            name="locations",
            field=models.ManyToManyField(
                through="archive.LocationReference", to="entities.location"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="people",
            field=models.ManyToManyField(
                through="archive.ResourceInvolvement", to="entities.person"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="topics",
            field=models.ManyToManyField(
                through="archive.TopicReference", to="entities.topic"
            ),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
