# Generated by Django 5.0.3 on 2024-03-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archive_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='media_type',
            field=models.CharField(default='video/mp4', max_length=100),
        ),
        migrations.AddField(
            model_name='interview',
            name='media_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='interview',
            name='poster',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='interview',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
