# Generated by Django 5.0.3 on 2024-03-14 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_topicreference_timecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicreference',
            name='timecode',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MetadataKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archive')),
            ],
        ),
        migrations.CreateModel(
            name='CharFieldMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.interview')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.metadatakey')),
            ],
        ),
    ]
