# Generated by Django 5.0.3 on 2024-03-09 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_interview_media_type_interview_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
