# Generated by Django 5.0.6 on 2024-06-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "archive",
            "0003_agent_remove_resource_people_agency_resource_agents_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transcript",
        ),
    ]
