# Generated by Django 5.0.3 on 2024-03-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_topicreference_timecode_metadatakey_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charfieldmetadata',
            options={'verbose_name_plural': 'char field metadata'},
        ),
        migrations.AddField(
            model_name='person',
            name='eastern_name_order',
            field=models.BooleanField(default=False),
        ),
    ]
