# Generated by Django 5.0.3 on 2024-03-09 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.interview')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.person')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='people',
            field=models.ManyToManyField(through='archive.InterviewInvolvement', to='archive.person'),
        ),
    ]
