# Generated by Django 5.0.3 on 2024-03-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_alter_person_options_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='metadatakey',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='archive',
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
