# Generated by Django 5.0.3 on 2024-03-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_interviewinvolvement_interview_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinvolvement',
            name='type',
            field=models.CharField(choices=[('INT', 'Interviewee'), ('ITR', 'Interviewer'), ('CAM', 'Camera'), ('SND', 'Sound'), ('EDT', 'Editor'), ('OTH', 'Other')], default='INT', max_length=3),
        ),
    ]
