# Generated by Django 5.0.3 on 2024-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_alter_interviewinvolvement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Diverse'), ('N', 'Not specified')], default='N', max_length=1),
        ),
    ]
