# Generated by Django 5.0.3 on 2024-03-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_location_locationreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='locations',
            field=models.ManyToManyField(through='archive.LocationReference', to='archive.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='geonames_id',
            field=models.IntegerField(blank=True),
        ),
    ]
