# Generated by Django 5.0.3 on 2024-03-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_alter_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gnd_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
