# Generated by Django 5.0.3 on 2024-03-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_person_gnd_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gnd_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='topics',
            field=models.ManyToManyField(to='archive.topic'),
        ),
    ]
