# Generated by Django 5.0.3 on 2024-03-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_interview_locations_alter_location_geonames_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geonames_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
