# Generated by Django 5.0.3 on 2024-03-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_topic_interview_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gnd_id',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='gnd_id',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
