# Generated by Django 5.0.3 on 2024-03-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_alter_location_geonames_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
