# Generated by Django 5.0.3 on 2024-03-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_alter_person_gnd_id_alter_topic_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='media_url',
            field=models.URLField(default='', max_length=300),
        ),
    ]
