# Generated by Django 5.0.3 on 2024-03-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_alter_interview_media_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('vtt', models.TextField()),
                ('language', models.CharField(max_length=5)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.interview')),
            ],
        ),
    ]
