# Generated by Django 5.0.6 on 2024-06-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "gnd_id",
                    models.CharField(
                        blank=True,
                        help_text="<a href='https://d-nb.info/standards/elementset/gnd'>GND</a> authority file identifier",
                        max_length=20,
                        verbose_name="GND id",
                    ),
                ),
            ],
            options={
                "verbose_name": "entity",
                "verbose_name_plural": "entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "entity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="entities.entity",
                    ),
                ),
                ("geonames_id", models.IntegerField(blank=True, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
            bases=("entities.entity",),
        ),
        migrations.CreateModel(
            name="MiscellaneousEntity",
            fields=[
                (
                    "entity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="entities.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "miscellaneous entity",
                "verbose_name_plural": "miscellaneous entities",
            },
            bases=("entities.entity",),
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "entity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="entities.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation",
                "verbose_name_plural": "organisation",
            },
            bases=("entities.entity",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "entity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="entities.entity",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                (
                    "eastern_name_order",
                    models.BooleanField(
                        default=False,
                        help_text="Select if the last name should appear first.",
                        verbose_name="eastern name order",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("D", "Diverse"),
                            ("N", "Not specified"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField()),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
                "ordering": ["last_name", "first_name"],
            },
            bases=("entities.entity",),
        ),
    ]
