# Generated by Django 5.0.6 on 2024-06-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["type"], name="entities_en_type_58b53d_idx"),
        ),
    ]
