# Generated by Django 5.0.6 on 2024-06-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "verbose_name": "organisation",
                "verbose_name_plural": "organisations",
            },
        ),
        migrations.AlterField(
            model_name="location",
            name="geonames_id",
            field=models.IntegerField(
                blank=True,
                help_text="<a href='https://www.geonames.org/'>GeoNames</a> geographical database identifier",
                null=True,
                verbose_name="GeoNames id",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="longitude"),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                default="", max_length=200, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("D", "Diverse"),
                    ("N", "Not specified"),
                ],
                default="N",
                max_length=1,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(max_length=200, verbose_name="last name"),
        ),
    ]
