# Generated by Django 5.0.6 on 2024-06-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0005_remove_topicreference_resource_and_more"),
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
