# Generated by Django 5.0.6 on 2024-06-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_entity_description_person_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                verbose_name="sex",
            ),
        ),
    ]
