# Generated by Django 5.0.6 on 2024-06-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_entity_entities_en_type_58b53d_idx"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="MiscellaneousEntity",
        ),
        migrations.DeleteModel(
            name="Organisation",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=models.CharField(
                choices=[
                    ("PER", "Person"),
                    ("LOC", "Location"),
                    ("ORG", "Organisation"),
                    ("MISC", "Misc"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
